name: Poet Experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    uses: itsbibeksaini/github-workflows/.github/workflows/gradle-build.yml@main
